### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [maybenextime/NumberWithDimension#1]
# Класс ReDimension

1. Когда вы создаёте `ReDimension` от `km/g*pa`, у вас получается размерность `m/g*a` со степенью `-9`. Так и было задумано?
2. Когда вы создаёте `NumbweWithDimension` от `5`, у вас получается размерность `5`. 5 должно быть числом, а размерность должна быть пустой.
3. Переименуйте геттеры и поля в соотс=ветствии с Java code style.
4. В конструкторе вы используете конкатенацию трок в цикле. Это неэффективно, лучше использовать `StringBuilder`.
5. Зачем вы храните в классе исходную строку? Вы её уже разобрали и получили нормированную размерность и степень.
6. Геттеры - это вообще какое-то безумие. Зачем создавать новый объект и заново разбирать строку? Почему нельзя использовать поля класса?
7. Отсутствуют `equals` и `hashCode`

# Класс `NumberWithDimension`

1. У вас же есть класс `ReDimension`. Зачем вы извлекаете строку из его объекта в конструкторе и домножаете число на степень? Можно просто хранить объект `ReDimension`.
2. Класс `NumberWithDimension` лучше сделать неизменяемым, то есть, сделать так, чтобы арифметические операторы возвращали новый объект, а не изменяли текущий.
3. Объявить о том, что с вашим объектом можно делать порядковое сравнение можно реализовав интерфейс `Comparable`. Собственно, вы почти сделали это, осталось объявить что вы его реализуете и переименовать метод правильно.

# Тесты

1. Тестами покрыта далеко не вся функциональность.
2. Сравнивать в тестах строковое представление никуда не годится. Сравнивайте ваше объекты на равенство с помощью `assertEquals`. Если `assertEquals` падает на одинаковых объектах, ищите баг в вашей реализации `equals`.

// equals/hashCode

**Comment by gagarski** [comment]
> Когда вы создаёте ReDimension от km/g*pa, у вас получается размерность m/g*a со степенью -9. Так и было задумано?

Удаление приставки "пико" - это не решение проблемы. Например, единица измерения количества вещества - моль обозначается "mol". Теперь уберёте приставку милли?

> Переименуйте геттеры и поля в соотс=ветствии с Java code style.

Зачем убрали геттеры?

> У вас же есть класс ReDimension. Зачем вы извлекаете строку из его объекта в конструкторе и домножаете число на степень? Можно просто хранить объект ReDimension.

Всё ещё актуально.

> Класс NumberWithDimension лучше сделать неизменяемым, то есть, сделать так, чтобы арифметические операторы возвращали новый объект, а не изменяли текущий.

Всё ещё актуально

> Объявить о том, что с вашим объектом можно делать порядковое сравнение можно реализовав интерфейс Comparable. Собственно, вы почти сделали это, осталось объявить что вы его реализуете и переименовать метод правильно.

Всё ещё актуально.

> Тестами покрыта далеко не вся функциональность.

Всё ещё актуально.

> Сравнивать в тестах строковое представление никуда не годится. Сравнивайте ваше объекты на равенство с помощью assertEquals. Если assertEquals падает на одинаковых объектах, ищите баг в вашей реализации equals.

Всё ещё актуально


Кроме того, с логикой разделения на классы после ваших исправлений стало ещё хуже. Раньше можно было создать `new ReDimension("km/g")`, теперь почему-то нужно `new ReDimension("10 km/g")`. Класс `ReDimension` же хранил единицу измерения, а число хранилось в `NumberWithDimension`. Теперь вообще непонятно кто за что отвечает.

**Comment by maybenextime** [comment]
- Я решил проблему"Pa", создав список, содержащий единицы измерения.
- Я снова добавил геттер .
-Числа были пересчитаны в ReDimension ;
-создал result  для считана;
-дополнил implements Comparable<NumberWithDimension>
-если new ReDimension("km/g") я throw new NumberFormatException();
- Можно показать мне какой функциональностьб который нет в тестом Я буду дополнить.

**Comment by gagarski** [comment]
> У вас же есть класс ReDimension. Зачем вы извлекаете строку из его объекта в конструкторе и домножаете число на степень? Можно просто хранить объект ReDimension.

Всё ещё актуально.

> Класс NumberWithDimension лучше сделать неизменяемым, то есть, сделать так, чтобы арифметические операторы возвращали новый объект, а не изменяли текущий.

Всё ещё актуально

> Объявить о том, что с вашим объектом можно делать порядковое сравнение можно реализовав интерфейс Comparable. Собственно, вы почти сделали это, осталось объявить что вы его реализуете и переименовать метод правильно.

Прочитайте что должен возвращать метод `compareTo` и сделайте как следует.

> Сравнивать в тестах строковое представление никуда не годится. Сравнивайте ваше объекты на равенство с помощью assertEquals. Если assertEquals падает на одинаковых объектах, ищите баг в вашей реализации equals.

Всё ещё актуально

> Кроме того, с логикой разделения на классы после ваших исправлений стало ещё хуже. Раньше можно было создать `new ReDimension("km/g")`, теперь почему-то нужно `new ReDimension("10 km/g")`. Класс `ReDimension` же хранил единицу измерения, а число хранилось в `NumberWithDimension`. Теперь вообще непонятно кто за что отвечает.

И это тоже всё ещё актуально.

**Comment by maybenextime** [comment]
Я сделал как вы говорили . Но поблем есть. например: 1km  и 1000m . Они равно. Но обект Redimension не одинаковые.   1km это Redimension(1000,m) .1m  это Redimension(1,m). Если я хочу считать 1km+1000m , я думаю,что мне нужно заменять  на Redimension (1 ,m) . Но когда равняться 2km или 2000m . Число нужно умножить на степен и  измерения заменяется на Redimenson (1,m) 
Если так я думаю сложно чем использовать обьект String
Можно мне решение этого проблема
